using RAMWatch.Core.Models;

namespace RAMWatch.Service.Services;

/// <summary>
/// Scans C:\Windows\LiveKernelReports\ for mini-dump files generated by WHEA
/// and other kernel error sources. These dumps are created without a full BSOD
/// and contain CPER (Common Platform Error Record) data.
///
/// The service runs as LocalSystem and has read access to this directory.
/// Scanned once at startup and on demand — these files change rarely.
/// </summary>
public static class LiveKernelReportScanner
{
    private static readonly string ReportsPath =
        Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.Windows), "LiveKernelReports");

    /// <summary>
    /// Scan the LiveKernelReports directory and return a summary.
    /// Returns null if the directory doesn't exist or is inaccessible.
    /// </summary>
    public static LiveKernelReportSummary? Scan()
    {
        try
        {
            if (!Directory.Exists(ReportsPath))
                return null;

            var allDumps = new List<(string Category, DateTime LastWrite)>();

            foreach (var subDir in Directory.EnumerateDirectories(ReportsPath))
            {
                string category = Path.GetFileName(subDir);
                try
                {
                    foreach (var file in Directory.EnumerateFiles(subDir, "*.dmp"))
                    {
                        try
                        {
                            var info = new FileInfo(file);
                            allDumps.Add((category, info.LastWriteTimeUtc));
                        }
                        catch
                        {
                            // Individual file inaccessible — skip
                        }
                    }
                }
                catch
                {
                    // Subdirectory inaccessible — skip
                }
            }

            if (allDumps.Count == 0)
                return null;

            var categories = allDumps
                .Select(d => d.Category)
                .Distinct(StringComparer.OrdinalIgnoreCase)
                .OrderBy(c => c)
                .ToList();

            int wheaCount = allDumps.Count(d =>
                d.Category.Equals("WHEA", StringComparison.OrdinalIgnoreCase));

            return new LiveKernelReportSummary
            {
                TotalCount = allDumps.Count,
                WheaCount = wheaCount,
                MostRecent = allDumps.Max(d => d.LastWrite),
                Oldest = allDumps.Min(d => d.LastWrite),
                Categories = categories
            };
        }
        catch
        {
            // Directory inaccessible — graceful degradation
            return null;
        }
    }
}
